### ISSUE TITLE
failure on first-run db creation...

### ISSUE THREAD

**Issue by easytarget** [easytarget/pi-overwatch#17]
Probably just needs a delay of 1s after creating, only happens when db newly created.
```
pi@transmog:~/HAT/pi-overwatch/TEST $ python ../overwatch.py
Working directory: /home/pi/HAT/pi-overwatch/TEST
Running: ../overwatch.py  @ 201cd7f-dirty
Using configuration from /home/pi/HAT/pi-overwatch/TEST/config.ini
Settings loaded from configuration file successfully
Starting OverWatch
Logging to: /home/pi/HAT/pi-overwatch/TEST/overwatch.log
Storable sources = ['sys-temp', 'sys-load', 'sys-mem']
Template = sys-temp:sys-load:sys-mem
Generating /home/pi/HAT/pi-overwatch/TEST/overwatch.rrd
 source: sys-temp (-10,110)
 source: sys-load (0,10)
 source: sys-mem (0,100)
RRD database and cache configured and enabled
overwatch.py :: 14:11:56, Wednesday, 03 November, 2021
Traceback (most recent call last):
  File "../overwatch.py", line 396, in <module>
    schedule.run_all()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 787, in run_all
    default_scheduler.run_all(delay_seconds=delay_seconds)
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 118, in run_all
    default_scheduler.run_all(delay_seconds=delay_seconds)
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 118, in run_all
    self._run_job(job)
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/home/pi/.local/lib/python3.7/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "../overwatch.py", line 296, in update_db
    rrd.update(data)
  File "/home/pi/HAT/pi-overwatch/robin.py", line 113, in update
    self.write_updates()
  File "/home/pi/HAT/pi-overwatch/robin.py", line 120, in write_updates
    *self.cache)
rrdtool.OperationalError: /home/pi/HAT/pi-overwatch/TEST/overwatch.rrd: illegal attempt to update using time 1635945116 when last update time is 1635945116 (minimum one second step)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "../overwatch.py", line 329, in good_bye
    rrd.write_updates()
  File "/home/pi/HAT/pi-overwatch/robin.py", line 120, in write_updates
    *self.cache)
rrdtool.OperationalError: /home/pi/HAT/pi-overwatch/TEST/overwatch.rrd: illegal attempt to update using time 1635945116 when last update time is 1635945116 (minimum one second step)
```

**Comment by easytarget** [comment]
Fixed by creating with `start='now-10s'`
